package= {name= 'ipc', version= '0.0.0', edition= '2021', description = 'Unix IPC'}
lib={path = 'lib.rs'}

[dependencies]
fehler= '*'
anyhow= '*'
serde= {version='*',features=["derive"]}
bincode= '*'
rustix= '*'
inotify= '*'
fork= '*'
